// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    // Test name: Login
    // Step # | name | target | value
    // 1 | open | /login?refUrl=/ | 
    driver.get("https://capp-test.aerchain.io/login?refUrl=/");
    // 2 | setWindowSize | 1920x982 | 
    driver.manage().window().setSize(new Dimension(1920, 982));
    // 3 | type | id=name | demoadmin@aerchain.io
    driver.findElement(By.id("name")).sendKeys("demoadmin@aerchain.io");
    // 4 | type | id=confirmPassword | 12345
    driver.findElement(By.id("confirmPassword")).sendKeys("12345");
    // 5 | click | id=name | 
    driver.findElement(By.id("name")).click();
    // 6 | click | id=name | 
    driver.findElement(By.id("name")).click();
    // 7 | click | id=name | 
    driver.findElement(By.id("name")).click();
    // 8 | mouseOver | css=.MuiButton-contained > .MuiButton-label | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | click | css=.MuiButton-contained > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    // 10 | click | css=.img-logo | 
    driver.findElement(By.cssSelector(".img-logo")).click();
    // 11 | click | css=.curved-button | 
    driver.findElement(By.cssSelector(".curved-button")).click();
  }
}
